# Generated by Django 4.0.4 on 2022-06-22 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('area', models.CharField(blank=True, max_length=200)),
                ('image', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.TextField(blank=True, default='Gokce Ozer')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('articles', models.ManyToManyField(blank=True, to='posts.article')),
            ],
        ),
    ]
